---
- name: 'Trigger an initramfs bootfile update'
  become: true
  command: '/usr/sbin/update-initramfs -u -k all'

- name: 'Load the mba6x_bl module'
  become: true
  command: '/sbin/modprobe mba6x_bl'

- name: 'restart-pcscd'
  become: true
  service:
    name: 'pcscd'
    state: 'restarted'

- name: 'macbook_setup-restart-docker'
  become: true
  service:
    name: 'docker'
    state: 'restarted'

- name: 'macbook_setup-apt-get-update'
  become: true
  apt:
    update_cache: yes

- name: 'restart-udev'
  become: true
  service:
    name: 'udev'
    state: 'restarted'

- name: 'reload-systemctl'
  become: true
  command: 'systemctl daemon-reload'
