---
- name: 'Put the /etc/sudoers file in place'
  become: true
  copy:
    src: 'sudoers'
    dest: '/etc/sudoers'
    owner: 'root'
    group: 'root'
    mode: '0440'
    validate: '/usr/sbin/visudo -cf %s'

- name: 'Put the /etc/sudoers.d/README file in place'
  become: true
  copy:
    src: 'README'
    dest: '/etc/sudoers.d/README'
    owner: 'root'
    group: 'root'
    mode: '0440'
    validate: '/usr/sbin/visudo -cf %s'
