---
- hosts: all
  vars_files:
    - 'vars/secret.yml'
    - 'vars/public.yml'
  connection: local
  roles:
    - 'bash'
    - 'xdg'
    - 'i3'
    - 'vim'
    - 'tmux'
    - 'git'
    - 'symlinks'
    - 'ssh_config'
    - 'irssi'
    - 'gpg'
    - 'backups'

    - role: 'set_gsettings_value'
      schema: 'org.gnome.settings-daemon.plugins.keyboard'
      key: 'active'
      value: 'false'
      expected_value: 'false'

    - role: 'set_gsettings_value'
      schema: 'org.gnome.desktop.lockdown'
      key: 'disable-lock-screen'
      value: 'true'
      expected_value: 'true'
