---
- hosts: all
  vars_files:
    - 'vars/secret.yml'
    - 'vars/public.yml'
  connection: local
  roles:
    - 'bash'
    - 'xdg'
    - 'i3'
    - 'vscode'
    - 'vim'
    - 'cheat'
    - 'tmux'
    - 'git'
    - 'symlinks'
    - 'ssh_config'
    - 'irssi'
    - 'gpg'
    - 'backups'
    - 'ngrok'
    - 'clical'
    - 'ranger'
    - 'nerd_fonts'
    - 'gnome_terminal'

    - role: 'set_gsettings_value'
      schema: 'org.gnome.settings-daemon.plugins.keyboard'
      key: 'active'
      value: 'false'

    - role: 'set_gsettings_value'
      schema: 'org.gnome.desktop.lockdown'
      key: 'disable-lock-screen'
      value: 'true'

    - role: 'set_gsettings_value'
      schema: 'org.gnome.desktop.background'
      key: 'show-desktop-icons'
      value: 'false'

    - role: 'set_gsettings_value'
      schema: 'org.gnome.desktop.peripherals.keyboard'
      key: 'repeat-interval'
      value: "20"

    - role: 'set_gsettings_value'
      schema: 'org.gnome.desktop.peripherals.keyboard'
      key: 'delay'
      value: "250"
