---
- hosts: all
  vars_files:
    - 'vars/secret.yml'
    - 'vars/public.yml'
  connection: local
  roles:
    - role: 'marvinpinto.docker'
      docker_additional_service_opts: |
        {
          "userns-remap": "marvin"
        }
    - role: 'user_account_wrapper'
      account_username: 'marvin'
      account_fullname: 'Marvin Pinto'
      account_passwordhash: "{{ marvin_passwordhash }}"
      account_sshkey: 'https://github.com/marvinpinto.keys'
      account_sudoers_entry: 'marvin ALL=(ALL) ALL'
      account_groups: 'docker'

    - role: 'sshd'
      sshd_enabled: 'no'
      sshd_state: 'stopped'

    - 'sudoers'
    - 'verbose_boot'

    - role: 'apt_repositories'
      ubuntu_base_repos:
        - 'deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main restricted'
        - 'deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates main restricted'
        - 'deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe'
        - 'deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates universe'
        - 'deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} multiverse'
        - 'deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates multiverse'
        - 'deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-backports main restricted universe multiverse'
        - 'deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security main restricted'
        - 'deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security universe'
        - 'deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security multiverse'
        - 'deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} partner'

    - role: 'apt_repositories'
      ubuntu_base_repos:
        - 'deb http://extras.ubuntu.com/ubuntu {{ ansible_distribution_release }} main'
      when:
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_version == "14.04"

    - 'macbook_setup'
    - 'locale'
    - 'lightdm'

    - role: 'delete_unmanaged_files'
      managed_files_directory: '/etc/X11/xorg.conf.d'
      managed_files:
        - '60-magictrackpad.conf'
        - '60-synaptics.conf'
        - '70-optical-mice.conf'

    - role: 'delete_unmanaged_files'
      managed_files_directory: '/etc/apt/sources.list.d'
      managed_files:
        - 'archive_canonical_com_ubuntu.list'
        - 'ppa_ansible_ansible_{{ ansible_distribution_release }}.list'
        - 'ansible-ubuntu-ansible-{{ ansible_distribution_release }}.list'
        - 'archive_ubuntu_com_ubuntu.list'
        - 'extras_ubuntu_com_ubuntu.list'
        - 'ppa_git_core_ppa_{{ ansible_distribution_release }}.list'
        - 'git-core-ubuntu-ppa-{{ ansible_distribution_release }}.list'
        - 'dl_google_com_linux_chrome_deb.list'
        - 'security_ubuntu_com_ubuntu.list'
        - 'download_virtualbox_org_virtualbox_debian.list'
        - 'apt_dockerproject_org_repo.list'
        - 'debian_sur5r_net_i3.list'
        - 'packagecloud_io_github_git_lfs_ubuntu.list'
        - 'ppa_yubico_stable_{{ ansible_distribution_release }}.list'
        - 'ppa_gertvdijk_ccid_backports_trusty.list'
        - 'ppa_nvidia_graphics_drivers.list'
        - 'ppa_peek_xenial.list'
        - 'ppa_jasonpleau_rofi_{{ ansible_distribution_release }}.list'
