---
- name: 'Create the ~/.irssi directory'
  file:
    path: '~/.irssi'
    owner: 'marvin'
    group: 'marvin'
    mode: '0700'
    state: directory

- name: 'Put the scripts directory in place'
  copy:
    src: 'scripts'
    dest: '~/.irssi/'
    owner: 'marvin'
    group: 'marvin'
    mode: '0644'

- name: 'Put the fear2.theme file in place'
  copy:
    src: 'fear2.theme'
    dest: "~/.irssi/fear2.theme"
    owner: 'marvin'
    group: 'marvin'
    mode: '0644'

- name: 'Put the config-im file in place'
  copy:
    content: |
      {{ config_im }}
      
    dest: '~/.irssi/config-im'
    owner: 'marvin'
    group: 'marvin'
    mode: '0600'

- name: 'Put the config-slack file in place'
  copy:
    content: |
      {{ config_slack }}
      
    dest: '~/.irssi/config-slack'
    owner: 'marvin'
    group: 'marvin'
    mode: '0600'
