---
- name: 'Create the ~/.irssi directory'
  file:
    path: '{{ home_directory }}/.irssi'
    owner: 'marvin'
    group: 'marvin'
    mode: '0700'
    state: directory

- name: 'Put the scripts directory in place'
  copy:
    src: 'scripts'
    dest: '{{ home_directory }}/.irssi/'
    owner: 'marvin'
    group: 'marvin'
    mode: '0644'

- name: 'Put the fear2.theme file in place'
  copy:
    src: 'fear2.theme'
    dest: "{{ home_directory }}/.irssi/fear2.theme"
    owner: 'marvin'
    group: 'marvin'
    mode: '0644'

- name: 'Put the config-im file in place'
  copy:
    content: |
      {{ config_im }}
      
    dest: '{{ home_directory }}/.irssi/config-im'
    owner: 'marvin'
    group: 'marvin'
    mode: '0600'

- name: 'Put the triggers save file in place'
  copy:
    content: |
      #Triggers file version 1.1
      -all -masks '*!gitter@*' -tags 'gitter-im' -regexp '(mar)(vin)' -replace '$1\x02\x02$2'
    dest: "{{ home_directory }}/.irssi/triggers"
    owner: 'marvin'
    group: 'marvin'
    mode: '0600'
