---
virtualbox_major_version: '5'
virtualbox_minor_version: '2'
virtualbox_patch_version: '0'
virtualbox_build_id: '118431'
digikam_version: '6.0.0'
kdenlive_version: '19.04.2f'
vagrant_version: '2.2.4'
prev_ranger_version: '1.9.1'
ranger_version: '1.9.2'
op_version: '0.5.6-003'
openaudible_version: '1.5.3'
