---
virtualbox_major_version: '5'
virtualbox_minor_version: '2'
virtualbox_patch_version: '0'
virtualbox_build_id: '118431'
plexamp_version: '1.1.0'
digikam_version: '6.0.0'
kdenlive_version: '18.12.1b'
