---
- name: 'Create the /usr/local/etc/onepassword directory'
  become: true
  file:
    path: '/usr/local/etc/onepassword'
    state: 'directory'
    mode: '0755'

- name: 'Check to see if op version {{op_version}} is already downloaded'
  become: true
  stat:
    path: '/usr/local/etc/onepassword/op-{{op_version}}'
  register: 'op_path'

- name: 'Create the /usr/local/etc/onepassword/op-{{op_version}}/ directory'
  become: true
  file:
    path: '/usr/local/etc/onepassword/op-{{op_version}}'
    state: 'directory'
    mode: '0755'
  when: 'op_path.stat.exists == False'

- name: 'Download the op package'
  become: true
  unarchive:
    src: 'https://cache.agilebits.com/dist/1P/op/pkg/v{{ op_version }}/op_linux_amd64_v{{ op_version }}.zip'
    dest: '/usr/local/etc/onepassword/op-{{op_version}}/'
    copy: 'no'
    exclude: 'op.sig'
  when: 'op_path.stat.exists == False'

- name: 'Symlink the op binary to /usr/local/bin'
  become: true
  file:
    src: '/usr/local/etc/onepassword/op-{{op_version}}/op'
    dest: '/usr/local/bin/op'
    state: 'link'
