---
- name: 'Add the ansible ubuntu repo'
  become: true
  apt_repository:
    repo: 'ppa:ansible/ansible'
    state: present
    update_cache: yes

- name: 'Install ansible'
  become: true
  apt:
    name: 'ansible'
    state: latest
