---
- name: 'Add the Dropbox apt signing key'
  sudo: yes
  apt_key:
    keyserver: 'keyserver.ubuntu.com'
    id: '5044912E'
    state: present

- name: 'Add the Dropbox ubuntu repo'
  sudo: yes
  apt_repository:
    repo: 'deb http://linux.dropbox.com/ubuntu {{ ansible_distribution_release }} main'
    state: present
    update_cache: yes

- name: 'Install Dropbox'
  sudo: yes
  apt:
    name: "dropbox"
    state: latest

- name: 'Fix the Dropbox "Unable to monitor filesystem" issue'
  sudo: yes
  lineinfile:
    dest: '/etc/sysctl.conf'
    state: present
    line: 'fs.inotify.max_user_watches = 100000'
