---
- name: 'Add the git ubuntu repo'
  become: true
  apt_repository:
    repo: 'ppa:git-core/ppa'
    state: present
    update_cache: yes

- name: 'Install git'
  become: true
  apt:
    name: 'git'
    state: latest

- name: 'Add the git-lfs apt signing key'
  become: true
  apt_key:
    url: 'https://packagecloud.io/github/git-lfs/gpgkey'
    state: present
  notify: 'macbook_setup-apt-get-update'

- meta: flush_handlers

- name: 'Install apt-transport-https'
  become: true
  apt:
    name: 'apt-transport-https'
    state: latest

- name: 'Add the git-lfs ubuntu repo'
  become: true
  apt_repository:
    repo: 'deb https://packagecloud.io/github/git-lfs/ubuntu/ {{ ansible_distribution_release }} main'
    state: present
    update_cache: yes

- name: 'Install git-lfs'
  become: true
  apt:
    name: 'git-lfs'
    state: latest

- name: 'Add the diff-so-fancy ubuntu repo'
  become: true
  apt_repository:
    repo: 'ppa:aos1/diff-so-fancy'
    state: 'present'
    update_cache: 'yes'

- name: 'Install diff-so-fancy'
  become: true
  apt:
    name: 'diff-so-fancy'
    state: 'present'
