---
- name: 'Add the Google apt signing key'
  become: true
  apt_key:
    url: 'https://dl.google.com/linux/linux_signing_key.pub'
    state: present

- name: 'Add the Google ubuntu repo'
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
    state: present
    update_cache: yes

- name: 'Install Google Chrome'
  become: true
  apt:
    name: "google-chrome-stable"
    state: latest

- name: 'Install Google Chrome Beta'
  become: true
  apt:
    name: "google-chrome-beta"
    state: latest
