---
- name: 'Set the hostname for the Lenovo X1 Carbon'
  become: true
  hostname:
    name: 'mp-laptop'
  when:
    - ansible_system_vendor == "LENOVO"
    - ansible_product_name == "20BS0032US"

- name: 'Set the hostname for the Dell T1700'
  become: true
  hostname:
    name: 'mp-desktop'
  when:
    - ansible_system_vendor == "Dell Inc."
    - ansible_product_name == "Precision T1700"
