---
- name: 'Install a few networking-related things'
  become: true
  apt:
    name:
      - 'wicd'
      - 'wicd-cli'
      - 'wicd-curses'
    state: latest

- name: 'Install a few networking things related to the X1 Carbon'
  become: true
  apt:
    name:
      - 'bcmwl-kernel-source'
      - 'linux-firmware-nonfree'
    state: latest
  when:
    - ansible_system_vendor == "LENOVO"
    - ansible_product_name == "20BS0032US"

- name: 'Stop the network-manager service'
  become: true
  service:
    name: 'network-manager'
    state: 'stopped'
    enabled: no

- name: 'Add marvin to the netdev group'
  become: true
  user:
    name: 'marvin'
    groups: 'netdev'
    append: yes

- name: 'Start the wicd service'
  become: true
  service:
    name: 'wicd'
    state: 'started'
    enabled: yes

- name: 'Wait until the Internet is accessible again'
  shell: curl --head --silent https://www.google.com
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: 30
  delay: 10
  changed_when: False
