---
- name: 'Add the peek ubuntu repo'
  become: true
  apt_repository:
    repo: 'ppa:peek-developers/stable'
    state: present
    update_cache: yes
    filename: 'ppa_peek_{{ ansible_distribution_release }}'

- name: 'Install peek'
  become: true
  apt:
    name: 'peek'
    state: latest
