---
- name: 'Check to see if /home/marvin/.gitconfig exists'
  stat:
    path: '/home/marvin/.gitconfig'
  register: gc

- name: 'Ensure that the proper permissions are set on /home/marvin/.gitconfig'
  become: true
  file:
    path: '/home/marvin/.gitconfig'
    owner: 'marvin'
    group: 'marvin'
    mode: '0644'
  when: gc.stat.isreg is defined and gc.stat.isreg
