---
- name: 'Add a PPA containing a newish version of rofi'
  become: true
  apt_repository:
    repo: 'ppa:jasonpleau/rofi'
    state: present
    update_cache: yes

- name: 'Install rofi'
  become: true
  apt:
    name: 'rofi'
    state: 'latest'

- name: 'Install some rofi-related goodies'
  become: true
  apt:
    name:
      - 'qalc'
      - 'gawk'
      - 'xdotool'
      - 'libxml2-utils'
    state: 'latest'

- name: 'Install rofi-pass (version 2.0.1)'
  become: true
  get_url:
    url: 'https://raw.githubusercontent.com/carnager/rofi-pass/2.0.1/rofi-pass'
    dest: '/usr/local/bin/rofi-pass'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the rofi-launcher script file in place'
  become: true
  copy:
    src: 'rofi-launcher.sh'
    dest: '/usr/local/bin/rofi-launcher'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the rofi-i3-locker script file in place'
  become: true
  copy:
    src: 'rofi-i3-locker.sh'
    dest: '/usr/local/bin/rofi-i3-locker'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the rofi-calc script file in place'
  become: true
  copy:
    content: |
      #!/usr/bin/env bash
      if [[ -n $* ]]; then
        echo "${1}"
        qalc -t $1 | tee >(xclip -selection clipboard >/dev/null)
      fi
    dest: '/usr/local/bin/rofi-calc'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the rofi-switch-workspaces script file in place'
  become: true
  copy:
    content: |
      #!/usr/bin/env bash
      if [ -z $@ ]; then
        function gen_workspaces()
        {
          i3-msg -t get_workspaces | jq --raw-output ".[] | (.name)" | sort -n
        }

        echo temporary; gen_workspaces
      else
          WORKSPACE=$@

          if [ x"temporary" = x"${WORKSPACE}" ]; then
            i3-msg workspace scratch >/dev/null
          elif [ -n "${WORKSPACE}" ]; then
            i3-msg workspace "${WORKSPACE}" >/dev/null
          fi
      fi
    dest: '/usr/local/bin/rofi-switch-workspaces'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the rofi-2fa script file in place'
  become: true
  copy:
    content: |
      #!/usr/bin/env bash
      pkill -9 scdaemon || true
      ykman oath &> /dev/null
      DMENU="rofi -dmenu"
      if [ $? -eq 0 ]; then
        ykman oath code -s $(ykman oath list | ${DMENU} -i -p "Select Credential" -no-custom) | xclip -selection "clipboard"
      fi
    dest: '/usr/local/bin/rofi-2fa'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the rofi-emoji script file in place'
  become: true
  copy:
    src: 'rofi-emoji.sh'
    dest: '/usr/local/bin/rofi-emoji'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the rofi-url-handler script file in place'
  become: true
  copy:
    src: 'rofi-url-handler.sh'
    dest: '/usr/local/bin/rofi-url-handler'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the url-cleaner script file in place'
  become: true
  copy:
    src: 'url-cleaner.py'
    dest: '/usr/local/bin/url-cleaner'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the fix-bluetooth-audio script file in place'
  become: true
  copy:
    src: 'fix-bluetooth-audio.sh'
    dest: '/usr/local/bin/fix-bluetooth-audio'
    owner: 'root'
    group: 'root'
    mode: '0755'
