---
- name: 'Add a PPA containing a newish version of rofi'
  become: true
  apt_repository:
    repo: 'ppa:jasonpleau/rofi'
    state: present
    update_cache: yes

- name: 'Install rofi'
  become: true
  apt:
    name: 'rofi'
    state: 'latest'

- name: 'Install some rofi-related goodies'
  become: true
  apt:
    name: '{{ item }}'
    state: 'latest'
  with_items:
    - 'qalc'
    - 'gawk'
    - 'xdotool'

- name: 'Install greenclip (version 3.2)'
  become: true
  get_url:
    url: 'https://github.com/erebe/greenclip/releases/download/3.2/greenclip'
    dest: '/usr/local/bin/greenclip'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Install rofi-pass (version 2.0.1)'
  become: true
  get_url:
    url: 'https://raw.githubusercontent.com/carnager/rofi-pass/2.0.1/rofi-pass'
    dest: '/usr/local/bin/rofi-pass'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the rofi-launcher script file in place'
  become: true
  copy:
    src: 'rofi-launcher.sh'
    dest: '/usr/local/bin/rofi-launcher'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the rofi-i3-locker script file in place'
  become: true
  copy:
    src: 'rofi-i3-locker.sh'
    dest: '/usr/local/bin/rofi-i3-locker'
    owner: 'root'
    group: 'root'
    mode: '0755'
