---
- name: 'Put the screenshot script file in place'
  sudo: yes
  copy:
    src: 'screenshot.sh'
    dest: '/usr/local/bin/screenshot'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the diff-highlight script file in place'
  sudo: yes
  copy:
    src: 'diff-highlight'
    dest: '/usr/local/bin/diff-highlight'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the acd-backup script file in place'
  become: true
  template:
    src: 'acd-backup.sh.j2'
    dest: '/usr/local/bin/acd-backup'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the bootstrap-projects script file in place'
  become: true
  template:
    src: 'bootstrap-projects.py.j2'
    dest: '/usr/local/bin/bootstrap-projects'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the custom-pinentry script file in place'
  become: true
  copy:
    content: |
      #!/bin/bash
      # choose pinentry depending on PINENTRY_USER_DATA
      # requires pinentry-curses and pinentry-gtk2
      # this *only works* with gpg 2
      # see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=802020
      case $PINENTRY_USER_DATA in
      gui)
        exec /usr/bin/pinentry "$@"
        ;;
      none)
        exit 1 # do not ask for passphrase
        ;;
      *)
        exec /usr/bin/pinentry-curses "$@"
      esac
    dest: '/usr/local/bin/custom-pinentry'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the gopro script file in place'
  become: true
  copy:
    src: 'gopro.sh'
    dest: '/usr/local/bin/gopro'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the bootstrap-op script file in place'
  become: true
  copy:
    content: |
      #!/usr/bin/env bash
      op signin {{ op_account_address }} {{ op_account_email }}
    dest: '/usr/local/bin/bootstrap-op'
    owner: 'root'
    group: 'root'
    mode: '0755'
