---
- name: 'Put the screenshot script file in place'
  sudo: yes
  copy:
    src: 'screenshot.sh'
    dest: '/usr/local/bin/screenshot'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the diff-highlight script file in place'
  sudo: yes
  copy:
    src: 'diff-highlight'
    dest: '/usr/local/bin/diff-highlight'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the acd-backup script file in place'
  become: true
  template:
    src: 'acd-backup.sh.j2'
    dest: '/usr/local/bin/acd-backup'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the 2fa script file in place'
  become: true
  copy:
    src: '2fa.sh'
    dest: '/usr/local/bin/2fa'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the bootstrap-projects script file in place'
  become: true
  template:
    src: 'bootstrap-projects.py.j2'
    dest: '/usr/local/bin/bootstrap-projects'
    owner: 'root'
    group: 'root'
    mode: '0755'
