---
- name: 'Put the screenshot script file in place'
  sudo: yes
  copy:
    src: 'screenshot.sh'
    dest: '/usr/local/bin/screenshot'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the diff-highlight script file in place'
  sudo: yes
  copy:
    src: 'diff-highlight'
    dest: '/usr/local/bin/diff-highlight'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Put the acd-backup script file in place'
  become: true
  copy:
    src: 'acd-backup.sh'
    dest: '/usr/local/bin/acd-backup'
    owner: 'root'
    group: 'root'
    mode: '0755'
