---
- name: 'Add the slack ubuntu repo'
  become: true
  apt_repository:
    repo: 'deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main'
    state: 'present'
    update_cache: 'yes'

- name: 'Install Slack'
  become: true
  apt:
    name: 'slack-desktop'
    state: 'latest'
