---
- name: 'Install tools needed to format + mount USB flash drives'
  become: true
  apt:
    name:
      - 'usbmount'
      - 'pmount'
      - 'gparted'
      - 'exfat-utils'
      - 'exfat-fuse'
      - 'udev'
    state: latest

- name: 'Automount any USB flash drives as UID/GID 1000 (user marvin)'
  become: true
  lineinfile:
    dest: '/etc/usbmount/usbmount.conf'
    state: 'present'
    line: 'FS_MOUNTOPTIONS="uid=1000,gid=1000"'
    regexp: '^FS_MOUNTOPTIONS='
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Put the usb-mount.sh script in place'
  become: true
  copy:
    src: 'usb-mount.sh'
    dest: '/usr/local/bin/usb-mount.sh'
    owner: 'root'
    group: 'root'
    mode: '0655'

- name: 'Add the rules file needed for auto mounting USB storage'
  become: true
  copy:
    src: '99-usb-storage-mount.rules'
    dest: '/etc/udev/rules.d/99-usb-storage-mount.rules'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'restart-udev'

- name: 'Install the usb-mount systemd service'
  copy:
    content: |
      [Unit]
      Description=Mount USB Drive on %i
      [Service]
      Type=oneshot
      RemainAfterExit=true
      ExecStart=/usr/local/bin/usb-mount.sh add %i
      ExecStop=/usr/local/bin/usb-mount.sh remove %i
    dest: '/etc/systemd/system/usb-mount@.service'
  notify: 'reload-systemctl'

- meta: flush_handlers
