---
- name: 'Create the /usr/local/etc/virtualbox directory'
  sudo: yes
  file:
    path: '/usr/local/etc/virtualbox'
    state: 'directory'
    mode: '0755'

- name: 'Add the virtualbox apt signing key'
  become: true
  apt_key:
    url: 'https://www.virtualbox.org/download/oracle_vbox_2016.asc'
    state: present

- name: 'Add the virtualbox apt signing key (14.04)'
  become: true
  apt_key:
    url: 'https://www.virtualbox.org/download/oracle_vbox.asc'
    state: present
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "14.04"

- name: 'Add the Virtualbox ubuntu repo'
  sudo: yes
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present
    update_cache: yes

- name: 'Install Virtualbox'
  sudo: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - 'virtualbox-{{virtualbox_major_version}}.{{virtualbox_minor_version}}'
    - 'dkms'

- name: 'Check to see if the extension pack file exists'
  sudo: yes
  stat:
    path: '/usr/local/etc/virtualbox/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox_major_version}}.{{virtualbox_minor_version}}.{{virtualbox_patch_version}}-{{virtualbox_build_id}}.vbox-extpack'
  register: extension_pack_binary

- name: 'Download the extension pack'
  sudo: yes
  get_url:
    url: 'http://download.virtualbox.org/virtualbox/{{virtualbox_major_version}}.{{virtualbox_minor_version}}.{{virtualbox_patch_version}}/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox_major_version}}.{{virtualbox_minor_version}}.{{virtualbox_patch_version}}-{{virtualbox_build_id}}.vbox-extpack'
    dest: '/usr/local/etc/virtualbox/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox_major_version}}.{{virtualbox_minor_version}}.{{virtualbox_patch_version}}-{{virtualbox_build_id}}.vbox-extpack'
    mode: '0755'
  when: extension_pack_binary.stat.exists == False

- name: 'Install the extension pack'
  sudo: yes
  shell: 'echo y | /usr/bin/VBoxManage extpack install --replace /usr/local/etc/virtualbox/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox_major_version}}.{{virtualbox_minor_version}}.{{virtualbox_patch_version}}-{{virtualbox_build_id}}.vbox-extpack'
  when: extension_pack_binary.stat.exists == False

- name: 'Add marvin to the vboxusers group'
  sudo: yes
  user:
    name: 'marvin'
    groups: 'vboxusers'
    append: yes
