---
- name: 'Add the vscode apt signing key'
  become: true
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: 'present'

- name: 'Add the vscode ubuntu repo'
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
    state: 'present'
    update_cache: 'yes'

- name: 'Install vscode'
  become: true
  apt:
    name: 'code'
    state: 'latest'
