---
- name: 'Create the /etc/X11/xorg.conf.d directory'
  become: true
  file:
    path: '/etc/X11/xorg.conf.d'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: directory

- name: 'Put the 60-magictrackpad.conf file in place'
  become: true
  copy:
    src: '60-magictrackpad.conf'
    dest: '/etc/X11/xorg.conf.d/60-magictrackpad.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Put the 60-synaptics.conf file in place'
  become: true
  copy:
    src: '60-synaptics.conf'
    dest: '/etc/X11/xorg.conf.d/60-synaptics.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Put the 70-optical-mice.conf file in place'
  become: true
  copy:
    src: '70-optical-mice.conf'
    dest: '/etc/X11/xorg.conf.d/70-optical-mice.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Install gnome-settings-daemon'
  become: true
  apt:
    name: 'gnome-settings-daemon'
    state: latest

- name: 'Ensure that X11 does not attempt to start gpg-agent automatically'
  become: true
  file:
    path: '/etc/X11/Xsession.d/90gpg-agent'
    state: 'absent'

- name: 'Ensure that X11 does not attempt to start ssh-agent automatically'
  become: true
  file:
    path: '/etc/X11/Xsession.d/90x11-common_ssh-agent'
    state: 'absent'
