---
- name: 'Add the yubikey ubuntu repo'
  become: true
  apt_repository:
    repo: 'ppa:yubico/stable'
    state: present
    update_cache: yes
    filename: 'ppa_yubico_stable_{{ ansible_distribution_release }}'

- name: 'Install a few requirements needed by the various yubikey tools'
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - 'python-usb'
    - 'gnupg2'
    - 'pinentry-curses'
    - 'pcscd'
    - 'scdaemon'
    - 'pcsc-tools'
  notify: 'restart-pcscd'

- name: 'Add the CCID Backports (libccid) ubuntu repo'
  become: true
  apt_repository:
    repo: 'ppa:gertvdijk/ccid-backports'
    state: present
    update_cache: yes
    filename: 'ppa_gertvdijk_ccid_backports_trusty'
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "14.04"

- name: 'Patch the /etc/libccid_Info.plist file - see https://github.com/Yubico/yubioath-desktop/issues/86'
  become: true
  apt:
    name: 'libccid'
    state: latest
  notify: 'restart-pcscd'
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "14.04"

- name: 'Install the Yubikey personalization tools'
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - 'yubikey-personalization'
    - 'yubikey-personalization-gui'
    - 'yubioath-desktop'

- name: 'Symlink /usr/bin/gpg2 to /usr/local/bin/gpg'
  become: true
  file:
    src: '/usr/bin/gpg2'
    dest: '/usr/local/bin/gpg'
    state: 'link'

- name: 'Put the yubitouch.sh script in place'
  become: true
  copy:
    src: 'yubitouch.sh'
    dest: '/usr/local/bin/yubitouch.sh'
    owner: 'root'
    group: 'root'
    mode: '0655'
