---
- name: 'Add the rules file needed for Yubikey'
  become: true
  copy:
    src: '70-u2f.rules'
    dest: '/etc/udev/rules.d/70-u2f.rules'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'restart-udev'

- name: 'Add the yubikey ubuntu repo'
  become: true
  apt_repository:
    repo: 'ppa:yubico/stable'
    state: present
    update_cache: yes
    filename: 'ppa_yubico_stable_trusty'

- name: 'Add the CCID Backports (libccid) ubuntu repo'
  become: true
  apt_repository:
    repo: 'ppa:gertvdijk/ccid-backports'
    state: present
    update_cache: yes
    filename: 'ppa_gertvdijk_ccid_backports_trusty'

- name: 'Install a few requirements needed by the various yubikey tools'
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - 'python-usb'
    - 'libccid'
    - 'gnupg2'
    - 'pinentry-curses'
    - 'pcscd'
    - 'scdaemon'
    - 'pcsc-tools'
  notify: 'restart-pcscd'

- name: 'Install the Yubikey personalization tools'
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - 'yubikey-personalization'
    - 'yubikey-personalization-gui'
    - 'yubioath-desktop'

- name: 'Symlink /usr/bin/gpg2 to /usr/local/bin/gpg'
  become: true
  file:
    src: '/usr/bin/gpg2'
    dest: '/usr/local/bin/gpg'
    state: 'link'

- name: 'Put the yubitouch.sh script in place'
  become: true
  copy:
    src: 'yubitouch.sh'
    dest: '/usr/local/bin/yubitouch.sh'
    owner: 'root'
    group: 'root'
    mode: '0655'
