---
- name: 'Create the ~/.config/ranger directory'
  file:
    path: '{{ home_directory }}/.config/ranger'
    owner: 'marvin'
    group: 'marvin'
    mode: '0700'
    state: 'directory'

- name: 'Put the ranger config files in place'
  copy:
    src: "{{ item }}"
    dest: "{{ home_directory }}/.config/ranger/{{ item }}"
    owner: 'marvin'
    group: 'marvin'
    mode: '0600'
  with_items:
    - 'rc.conf'
