---
- name: 'Create the ~/.config directory'
  file:
    path: '{{ home_directory }}/.config'
    owner: 'marvin'
    group: 'marvin'
    mode: '0700'
    state: directory

- name: 'Create the ~/crap directory'
  file:
    path: '{{ home_directory }}/crap'
    owner: 'marvin'
    group: 'marvin'
    mode: '0700'
    state: directory

- name: 'Delete the following directories'
  file:
    path: "{{ home_directory }}/{{ item }}"
    state: absent
  with_items:
    - 'Desktop'
    - 'Downloads'
    - 'Templates'
    - 'Public'
    - 'Documents'
    - 'Music'
    - 'Pictures'
    - 'Videos'

- name: 'Put the user-dirs.dirs file in place'
  copy:
    src: 'user-dirs.dirs'
    dest: '{{ home_directory }}/.config/user-dirs.dirs'
    owner: 'marvin'
    group: 'marvin'
    mode: '0644'

- name: 'Create the ~/.config/gtk-3.0 directory'
  file:
    path: '{{ home_directory }}/.config/gtk-3.0'
    owner: 'marvin'
    group: 'marvin'
    mode: '0700'
    state: directory

- name: 'Put the gtk settings file in place'
  copy:
    src: 'gtk-settings.ini'
    dest: '{{ home_directory }}/.config/gtk-3.0/settings.ini'
    owner: 'marvin'
    group: 'marvin'
    mode: '0644'

- name: 'Put the mimeapps.list file in place'
  copy:
    src: 'default-applications.list'
    dest: "{{ home_directory }}/.local/share/applications/mimeapps.list"
    owner: 'marvin'
    group: 'marvin'
    mode: '0644'

- name: 'Put the defaults.list file in place'
  copy:
    src: 'default-applications.list'
    dest: "{{ home_directory }}/.local/share/applications/defaults.list"
    owner: 'marvin'
    group: 'marvin'
    mode: '0644'
