---
- name: 'Create the ~/.i3 directory'
  file:
    path: '{{ home_directory }}/.i3'
    owner: 'marvin'
    group: 'marvin'
    mode: '0700'
    state: directory

- name: 'Put the base i3 config files in place'
  copy:
    src: "{{ item }}"
    dest: "{{ home_directory }}/.i3/{{ item }}"
    owner: 'marvin'
    group: 'marvin'
    mode: '0644'
  with_items:
    - 'fastmail_username.gpg'
    - 'fastmail_password.gpg'

- name: 'Put the X1 Carbon i3 config file in place'
  copy:
    src: "i3config-lenovo"
    dest: "{{ home_directory }}/.i3/config"
    owner: 'marvin'
    group: 'marvin'
    mode: '0644'
  when:
    - ansible_system_vendor == "LENOVO"
    - ansible_product_name == "20BS0032US"

- name: 'Put the Dell T1700 i3 config file in place'
  copy:
    src: "i3config-dell"
    dest: "{{ home_directory }}/.i3/config"
    owner: 'marvin'
    group: 'marvin'
    mode: '0644'
  when:
    - ansible_system_vendor == "Dell Inc."
    - ansible_product_name == "Precision T1700"

- name: 'Put the X1 Carbon i3 statusbar config file in place'
  copy:
    src: "i3status-lenovo.conf"
    dest: "{{ home_directory }}/.i3/i3status.conf"
    owner: 'marvin'
    group: 'marvin'
    mode: '0644'
  when:
    - ansible_system_vendor == "LENOVO"
    - ansible_product_name == "20BS0032US"

- name: 'Put the Dell T1700 i3 statusbar config file in place'
  copy:
    src: "i3status-dell.conf"
    dest: "{{ home_directory }}/.i3/i3status.conf"
    owner: 'marvin'
    group: 'marvin'
    mode: '0644'
  when:
    - ansible_system_vendor == "Dell Inc."
    - ansible_product_name == "Precision T1700"

- name: 'Put the i3 executable files in place'
  copy:
    src: "{{ item }}"
    dest: "{{ home_directory }}/.i3/{{ item }}"
    owner: 'marvin'
    group: 'marvin'
    mode: '0755'
  with_items:
    - 'gpg-agent.sh'
    - 'restore-layout.sh'
    - 'wrapper.py'
    - 'fastmail_unread_count.py'
    - 'rename_workspace.sh'
    - 'pavolume.sh'
    - 'startup-app.sh'
    - 'tmux-startup.sh'
    - 'new-firefox-process.sh'
    - 'terminal-output-test.sh'

- name: 'Put the other X11 based files in place'
  copy:
    src: "{{ item }}"
    dest: "{{ home_directory }}/.{{ item }}"
    owner: 'marvin'
    group: 'marvin'
    mode: '0444'
  with_items:
    - 'xresources'
    - 'xmodmap'

- name: 'Put the ~/.i3/add-op-ssh-keys.sh file in place'
  copy:
    content: |
      #!/usr/bin/env bash
      # Note: this file is automatically generated
      export PINENTRY_USER_DATA=curses
      tmp_dir=$(mktemp -d -t op-XXXXXXXXXX)
      {% for item in op_ssh_keys %}
      mkfifo -m=600 $tmp_dir/op-fifo
      op get document --vault="{{ item.vault }}" "{{ item.document_name }}" > $tmp_dir/op-fifo | ssh-add $tmp_dir/op-fifo
      rm $tmp_dir/op-fifo
      {% endfor %}
      rm -rf "$tmp_dir"
    dest: '{{ home_directory }}/.i3/add-op-ssh-keys.sh'
    owner: 'marvin'
    group: 'marvin'
    mode: '0755'
    force: 'yes'
  no_log: true
