---
- name: 'Put the git config files in place'
  copy:
    src: "{{ item }}"
    dest: "{{ home_directory }}/.{{ item }}"
    owner: 'marvin'
    group: 'marvin'
    mode: '0644'
  with_items:
    - 'gitconfig'
    - 'gitignore_global'
