---
- shell: 'ls -1 {{ managed_files_directory }}'
  become: true
  changed_when: false
  register: contents

- name: 'Delete everything in the {{ managed_files_directory }} directory that is not managed by us'
  become: true
  file:
    path: '{{ managed_files_directory }}/{{ item }}'
    state: 'absent'
  with_items: '{{ contents.stdout_lines }}'
  when: item not in managed_files
