---
- name: 'Create the ~/.gnupg directory'
  file:
    path: '{{ home_directory }}/.gnupg'
    state: 'directory'
    mode: '0700'
    force: 'yes'

- name: 'Put the ~/.gnupg/gpg-agent.conf file in place'
  template:
    src: 'gpg-agent.conf.j2'
    dest: '{{ home_directory }}/.gnupg/gpg-agent.conf'
    mode: '0600'
    force: 'yes'

- name: 'Put the ~/.gnupg/gpg.conf file in place'
  template:
    src: 'gpg.conf.j2'
    dest: '{{ home_directory }}/.gnupg/gpg.conf'
    mode: '0600'
    force: 'yes'
