---
- name: 'Create the ~/.ssh directory'
  file:
    path: '{{ home_directory }}/.ssh'
    state: 'directory'
    mode: '0700'
    force: 'yes'

- name: 'Put the ~/.ssh/config file in place'
  template:
    src: 'ssh_config.j2'
    dest: '{{ home_directory }}/.ssh/config'
    mode: '0444'
    force: 'yes'
