---
- name: 'Install sshd'
  become: true
  apt:
    pkg: 'openssh-server'
    state: present

- name: 'Ensure that sshd autostarts'
  become: true
  service:
    name: 'ssh'
    enabled: "{{ sshd_enabled | default(yes) }}"
    state: "{{ sshd_state | default(started) }}"

- name: 'Create the /etc/ssh/authorized_keys directory'
  become: true
  file:
    path: '/etc/ssh/authorized_keys'
    owner: 'root'
    group: 'root'
    state: directory

- name: 'Configure sshd'
  become: true
  copy:
    src: 'sshd_config'
    dest: '/etc/ssh/sshd_config'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Restart sshd'
